ALTER TABLE notifications
  ADD COLUMN external_purpose text,
  ADD COLUMN external_channel text NOT NULL DEFAULT 'IN_APP_ONLY'
    CHECK (external_channel IN ('IN_APP_ONLY','WECHAT_SUBSCRIPTION')),
  ADD COLUMN template_slot text,
  ADD COLUMN external_scheduled_at timestamptz,
  ADD COLUMN external_dispatch_started_at timestamptz,
  ADD COLUMN provider_responded_at timestamptz,
  ADD COLUMN external_failure_code text;

-- Historical rows retain their actual outcome. The old consent did not grant
-- every operational kind; metadata here describes intent, not authorization.
UPDATE notifications n SET
  external_purpose=CASE n.kind
    WHEN 'EVENT_REMINDER' THEN 'EVENT_REMINDER'
    WHEN 'REGISTRATION_STATUS' THEN 'REGISTRATION_RESULT'
    WHEN 'REGISTRATION_APPROVED' THEN 'REGISTRATION_RESULT'
    WHEN 'REGISTRATION_REMOVED' THEN 'REGISTRATION_RESULT'
    WHEN 'WAITLIST_OFFER' THEN 'WAITLIST_OFFER'
    WHEN 'WAITLIST_WINDOW_CLOSED' THEN 'WAITLIST_WINDOW'
    WHEN 'MATERIAL_CHANGE' THEN 'EVENT_CHANGE'
    WHEN 'EVENT_CONFIRMED' THEN 'EVENT_FORMATION'
    WHEN 'EVENT_CANCELLED' THEN 'EVENT_CANCELLATION'
    WHEN 'EVENT_EXPIRED' THEN 'EVENT_CANCELLATION'
    WHEN 'MANUAL_CHECKIN_REQUEST' THEN 'CHECKIN_REQUEST'
    WHEN 'EVENT_SAFETY_PAUSED' THEN 'EVENT_SAFETY'
    WHEN 'EVENT_SAFETY_RESUMED' THEN 'EVENT_SAFETY'
    WHEN 'EVENT_SAFETY_REVIEW_CLOSED' THEN 'EVENT_SAFETY'
    WHEN 'EVENT_REVIEW_APPROVED' THEN 'EVENT_REVIEW_RESULT'
    WHEN 'EVENT_REVIEW_REJECTED' THEN 'EVENT_REVIEW_RESULT'
    ELSE 'UNCONFIGURED_KIND' END,
  external_channel='WECHAT_SUBSCRIPTION',
  template_slot=CASE n.kind
    WHEN 'EVENT_REMINDER' THEN 'EVENT_START_REMINDER'
    WHEN 'REGISTRATION_STATUS' THEN 'REGISTRATION_RESULT'
    WHEN 'REGISTRATION_APPROVED' THEN 'REGISTRATION_RESULT'
    WHEN 'REGISTRATION_REMOVED' THEN 'REGISTRATION_RESULT'
    WHEN 'WAITLIST_OFFER' THEN 'WAITLIST_OFFER'
    WHEN 'WAITLIST_WINDOW_CLOSED' THEN 'WAITLIST_WINDOW'
    WHEN 'MATERIAL_CHANGE' THEN 'EVENT_CHANGE'
    WHEN 'EVENT_CONFIRMED' THEN 'EVENT_FORMATION'
    WHEN 'EVENT_CANCELLED' THEN 'EVENT_CANCELLATION'
    WHEN 'EVENT_EXPIRED' THEN 'EVENT_CANCELLATION'
    WHEN 'MANUAL_CHECKIN_REQUEST' THEN 'CHECKIN_REQUEST'
    WHEN 'EVENT_SAFETY_PAUSED' THEN 'EVENT_SAFETY'
    WHEN 'EVENT_SAFETY_RESUMED' THEN 'EVENT_SAFETY'
    WHEN 'EVENT_SAFETY_REVIEW_CLOSED' THEN 'EVENT_SAFETY'
    WHEN 'EVENT_REVIEW_APPROVED' THEN 'EVENT_REVIEW_RESULT'
    WHEN 'EVENT_REVIEW_REJECTED' THEN 'EVENT_REVIEW_RESULT'
    ELSE n.kind END,
  external_scheduled_at=(SELECT min(j.due_at) FROM jobs j
    WHERE j.kind='SEND_EXTERNAL' AND j.payload->>'notificationId'=n.id)
WHERE EXISTS (SELECT 1 FROM jobs j WHERE j.kind='SEND_EXTERNAL'
  AND j.payload->>'notificationId'=n.id);
