export interface ExternalNoticeContract {
  externalPurpose: string;
  externalChannel: 'WECHAT_SUBSCRIPTION';
  templateSlot: string;
}

const contracts: Record<string, readonly [purpose: string, templateSlot: string]> = {
  EVENT_REMINDER: ['EVENT_REMINDER', 'EVENT_START_REMINDER'],
  REGISTRATION_STATUS: ['REGISTRATION_RESULT', 'REGISTRATION_RESULT'],
  REGISTRATION_APPROVED: ['REGISTRATION_RESULT', 'REGISTRATION_RESULT'],
  REGISTRATION_REMOVED: ['REGISTRATION_RESULT', 'REGISTRATION_RESULT'],
  WAITLIST_OFFER: ['WAITLIST_OFFER', 'WAITLIST_OFFER'],
  WAITLIST_WINDOW_CLOSED: ['WAITLIST_WINDOW', 'WAITLIST_WINDOW'],
  MATERIAL_CHANGE: ['EVENT_CHANGE', 'EVENT_CHANGE'],
  EVENT_CONFIRMED: ['EVENT_FORMATION', 'EVENT_FORMATION'],
  EVENT_CANCELLED: ['EVENT_CANCELLATION', 'EVENT_CANCELLATION'],
  EVENT_EXPIRED: ['EVENT_CANCELLATION', 'EVENT_CANCELLATION'],
  MANUAL_CHECKIN_REQUEST: ['CHECKIN_REQUEST', 'CHECKIN_REQUEST'],
  EVENT_SAFETY_PAUSED: ['EVENT_SAFETY', 'EVENT_SAFETY'],
  EVENT_SAFETY_RESUMED: ['EVENT_SAFETY', 'EVENT_SAFETY'],
  EVENT_SAFETY_REVIEW_CLOSED: ['EVENT_SAFETY', 'EVENT_SAFETY'],
  EVENT_REVIEW_APPROVED: ['EVENT_REVIEW_RESULT', 'EVENT_REVIEW_RESULT'],
  EVENT_REVIEW_REJECTED: ['EVENT_REVIEW_RESULT', 'EVENT_REVIEW_RESULT']
};

// An unmapped future kind remains visible in app but cannot inherit a grant.
export function externalNoticeContract(kind: string): ExternalNoticeContract {
  const [externalPurpose, templateSlot] = contracts[kind] ?? ['UNCONFIGURED_KIND', kind];
  return { externalPurpose, externalChannel: 'WECHAT_SUBSCRIPTION', templateSlot };
}
